#!/usr/bin/env python3
"""Drive three ordinary SLASH'EM tty processes; Python/pyte are test-only.

Evidence is real PTY output and its interpreted screen, never generated game
state. Map continuity compares all 80x21 displayed cells without normalization.
The dungeon is generated by the unmodified game; continuity is within this run,
not a comparison with a seeded fixture from another run.

The shell realizes GUI/Python dependencies only for acceptance and compares NARs. This
driver owns its offline user/mount/network/PID namespaces and fails closed.
"""
import argparse
import codecs
import ctypes
import errno
import fcntl
import hashlib
import json
import os
import pty
import tty
from pathlib import Path
import re
import select
import shutil
import signal
import socket
import struct
import subprocess
import sys
import tempfile
import termios
import time

import pyte

ROWS, COLS = 24, 100
NAME = 'OmpProof'
# Explicit native role/race/gender/alignment arguments select an ordinary
# local Valkyrie; no explore mode, wizard commands, seed patch or fake frontend.
PLAYER = NAME + '-Val-Hum-Fem-Law'
OPTIONS = ('windowtype:tty,time,!IBMgraphics,!DECgraphics,!color,'
           '!statuscolors,!legacy,!news,!splash_screen,!autopickup,'
           'menustyle:full,number_pad:0')


def require(condition, description):
    if not condition:
        raise RuntimeError(description)


def write_json(path, value):
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + '\n')


def write_all(fd, data):
    pending = memoryview(data)
    while pending:
        size = os.write(fd, pending)
        require(size > 0, 'PTY write made no progress')
        pending = pending[size:]


def relay(argv):
    """Forward only native PTY bytes to xterm; socket carries player input."""
    program, raw_path, status_path, socket_path, env_path, work = argv
    env = json.loads(Path(env_path).read_text())
    listener = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    listener.bind(socket_path)
    listener.listen(1)
    listener.settimeout(15)
    pid, master = pty.fork()
    if pid == 0:
        try:
            os.chdir(work)
            fcntl.ioctl(0, termios.TIOCSWINSZ,
                        struct.pack('HHHH', ROWS, COLS, 0, 0))
            os.execve(program, [program, '-n', '-u', PLAYER, '-p', 'Valkyrie',
                                '-r', 'human', '-g', 'female', '-a', 'lawful'], env)
        except BaseException:
            os._exit(127)
    previous = termios.tcgetattr(0)
    transport = None
    reaped = False
    def interrupted(signum, frame):
        raise RuntimeError('native relay interrupted: ' + str(signum))
    signal.signal(signal.SIGHUP, interrupted)
    signal.signal(signal.SIGTERM, interrupted)
    try:
        tty.setraw(0)
        transport, _ = listener.accept()
        with open(raw_path, 'ab', buffering=0) as raw, \
                open(raw_path + '.input', 'xb', buffering=0) as inputs:
            while True:
                ready, _, _ = select.select([0, master, transport], [], [], 1)
                if master in ready:
                    try:
                        chunk = os.read(master, 65536)
                    except OSError as error:
                        if error.errno != errno.EIO:
                            raise
                        break
                    if not chunk:
                        break
                    raw.write(chunk)
                    write_all(1, chunk)
                for source in (0, transport):
                    if source in ready:
                        chunk = (os.read(0, 4096) if source == 0
                                 else transport.recv(4096))
                        require(chunk, 'native relay input transport closed')
                        inputs.write(chunk)
                        write_all(master, chunk)
        _, status = os.waitpid(pid, 0)
        reaped = True
        code = os.waitstatus_to_exitcode(status)
        pending = Path(status_path + '.pending')
        pending.write_text(str(code) + '\n')
        pending.replace(status_path)
        return code
    finally:
        if not reaped:
            os.kill(pid, signal.SIGKILL)
            os.waitpid(pid, 0)
        termios.tcsetattr(0, termios.TCSANOW, previous)
        os.close(master)
        if transport is not None:
            transport.close()
        listener.close()
        Path(socket_path).unlink(missing_ok=True)

def mount(source, target, filesystem=None, flags=0):
    # Use the native syscall, not mount(8)'s real-UID-zero policy.  Namespace
    # capabilities are retained by unshare while xterm keeps the caller UID.
    libc = ctypes.CDLL(None, use_errno=True)
    libc.mount.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p,
                           ctypes.c_ulong, ctypes.c_void_p]
    libc.mount.restype = ctypes.c_int
    if libc.mount(os.fsencode(source), os.fsencode(target),
                  None if filesystem is None else os.fsencode(filesystem),
                  flags, None) != 0:
        error = ctypes.get_errno()
        raise OSError(error, os.strerror(error), str(target))



def private_tmp(output):
    # Hide host X sockets/locks without changing the caller's evidence inode.
    require(not Path(__file__).resolve().is_relative_to('/tmp') and
            not Path(sys.executable).resolve().is_relative_to('/tmp'),
            'checkout and Python must be outside host /tmp')
    evidence_fd = os.open(output, os.O_RDONLY | os.O_DIRECTORY)
    try:
        mount('tmpfs', '/tmp', 'tmpfs', 2 | 4)  # MS_NOSUID | MS_NODEV
        os.chmod('/tmp', 0o1777)
        private = Path('/tmp/slashem-evidence')
        private.mkdir(mode=0o700)
        mount(f'/proc/self/fd/{evidence_fd}', private, flags=4096)  # MS_BIND
    finally:
        os.close(evidence_fd)
    return private


class Display:
    def __init__(self, output):
        self.env = {key: os.environ[key] for key in
                    ('PATH', 'GUIX_PYTHONPATH', 'PYTHONPATH', 'TERMINFO', 'TERMINFO_DIRS')
                    if os.environ.get(key)}
        self.env['LC_ALL'] = 'C'
        self.root = Path('/tmp/native-display')
        self.root.mkdir(mode=0o700)
        for variable in ('HOME', 'XDG_CONFIG_HOME', 'XDG_DATA_HOME', 'XDG_STATE_HOME',
                         'XDG_CACHE_HOME', 'XDG_RUNTIME_DIR', 'TMPDIR'):
            directory = self.root / variable.lower()
            directory.mkdir(mode=0o700)
            self.env[variable] = str(directory)
        self.log = (output / 'xvfb.log').open('xb')
        read_fd, write_fd = os.pipe()
        try:
            self.process = subprocess.Popen(
                ['Xvfb', '-displayfd', str(write_fd), '-screen', '0',
                 '1920x1200x24', '-nolisten', 'tcp', '-ac'],
                pass_fds=(write_fd,), stdout=self.log, stderr=self.log, env=self.env)
        finally:
            os.close(write_fd)
        try:
            require(select.select([read_fd], [], [], 10)[0],
                    'Xvfb did not announce a display')
            display = os.read(read_fd, 64).decode('ascii').strip()
            require(display.isdigit(), 'invalid Xvfb display announcement')
            self.env['DISPLAY'] = ':' + display
        except BaseException:
            self.close()
            raise
        finally:
            os.close(read_fd)

    def close(self):
        self.process.terminate()
        try:
            self.process.wait(timeout=3)
        except subprocess.TimeoutExpired:
            self.process.kill()
            self.process.wait()
        self.log.close()


class Screen(pyte.Screen):
    last_graphic = ''

    def draw(self, data):
        super().draw(data)
        if data:
            self.last_graphic = data[-1]

    def repeat_character(self, count=1):
        if self.last_graphic:
            super().draw(self.last_graphic * (count or 1))


class Stream(pyte.Stream):
    csi = dict(pyte.Stream.csi, b='repeat_character')
    events = pyte.Stream.events | {'repeat_character'}


class Session:
    def __init__(self, executable, env, root, output, number, gui_env):
        self.output = output
        self.label = 'session-' + str(number)
        self.raw_path = output / (self.label + '.pty')
        self.raw_path.touch(exist_ok=False)
        self.raw = bytearray()
        self.offset = 0
        self.screen = Screen(COLS, ROWS)
        self.stream = Stream(self.screen)
        self.stream.use_utf8 = False
        self.decoder = codecs.getincrementaldecoder('utf-8')('replace')
        self.status = None
        self.eof = False
        self.deadline = time.monotonic() + 75
        self.argv = [executable, '-n', '-u', PLAYER, '-p', 'Valkyrie',
                     '-r', 'human', '-g', 'female', '-a', 'lawful']
        self.status_path = output / (self.label + '-exit-status.txt')
        self.socket_path = root / (self.label + '.sock')
        env_path = root / (self.label + '-game-env.json')
        write_json(env_path, env)
        self.gui_env = gui_env
        self.window = None
        self.transport = None
        self.stderr = (output / (self.label + '-xterm.log')).open('xb')
        command = ['xterm', '-geometry', f'{COLS}x{ROWS}', '-fa', 'Monospace',
                   '-fs', '14', '-bg', 'black', '-fg', 'white',
                   '-title', "SLASH'EM native proof " + str(number),
                   '-e', sys.executable, '-B', str(Path(__file__).resolve()),
                   '--relay', executable, str(self.raw_path), str(self.status_path),
                   str(self.socket_path), str(env_path), str(root / 'work')]
        self.process = subprocess.Popen(command, env=gui_env, stdout=self.stderr,
                                        stderr=self.stderr, start_new_session=True)
        try:
            end = time.monotonic() + 15
            while not self.socket_path.exists() or self.window is None:
                require(self.process.poll() is None, 'xterm exited before native relay was ready')
                require(time.monotonic() < end, 'xterm/relay startup timed out')
                found = self.command('xdotool', 'search', '--onlyvisible', '--pid',
                                     str(self.process.pid), check=False)
                if found.returncode == 0 and found.stdout.split():
                    self.window = found.stdout.split()[-1].decode('ascii')
                time.sleep(0.05)
            self.transport = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            self.transport.connect(str(self.socket_path))
        except BaseException:
            self.close()
            raise

    def command(self, *args, check=True):
        return subprocess.run(args, env=self.gui_env, stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE, check=check, timeout=10)

    def image(self, label, filename=None):
        # Capture the live X window after the native redraw has drained. No
        # terminal replay, rasterizer, OCR copy, or injected display bytes.
        self.settle()
        time.sleep(0.15)
        require(not self.exited() and self.window is not None, 'no live native X window')
        path = self.output / (filename or (self.label + '-' + label + '.png'))
        self.command('import', '-window', self.window, str(path))
        data = path.read_bytes()
        require(data[:8] == b'\x89PNG\r\n\x1a\n', 'live X capture is not PNG')
        width, height = struct.unpack('>II', data[16:24])
        require(width >= 640 and height >= 400, 'native X window too small')
        return {'path': path.name, 'sha256': hashlib.sha256(data).hexdigest(),
                'width': width, 'height': height, 'window': self.window,
                'source': 'ImageMagick import of live xterm window',
                'terminal_raw_sha256': hashlib.sha256(self.raw).hexdigest()}

    def text(self):
        return '\n'.join(self.screen.display)

    def read(self, delay=0.1):
        require(time.monotonic() < self.deadline,
                self.label + ': global deadline exceeded\n' + self.text())
        time.sleep(delay)
        with self.raw_path.open('rb') as stream:
            stream.seek(self.offset)
            data = stream.read()
        self.offset += len(data)
        if data:
            self.raw.extend(data)
            self.stream.feed(self.decoder.decode(data))
            require(len(self.raw) < 8000000, 'excessive native terminal output')
        if self.status_path.exists():
            self.status = int(self.status_path.read_text().strip())
            self.eof = True
        return bool(data)

    def exited(self):
        if self.status is None and self.status_path.exists():
            self.status = int(self.status_path.read_text().strip())
        return self.status is not None

    def send(self, keys):
        require(not self.exited(), self.label + ': process already exited')
        self.transport.sendall(keys.encode('ascii'))

    def settle(self):
        # Drain output, not a surrogate for the action-specific assertions.
        while self.read(0.25):
            pass

    def wait(self, predicate, what, more=True):
        end = time.monotonic() + 15
        while True:
            self.read()
            if more and '--More--' in self.text():
                self.send(' ')
                self.settle()
                continue
            if predicate():
                self.settle()
                if predicate():
                    return
            require(not self.exited(), what + ': exited\n' + self.text())
            require(time.monotonic() < end, what + ': timed out\n' + self.text())

    def snapshot(self, label):
        stem = self.label + '-' + label
        (self.output / (stem + '.pty')).write_bytes(self.raw)
        (self.output / (stem + '.screen.txt')).write_text(self.text() + '\n')
        return stem

    def live(self, label):
        self.send('\x12')  # Native redraw, no turns, no synthetic screen bytes.
        self.settle()
        lines = self.screen.display
        hud = lines[22:24]
        require('St:' in hud[0] and 'HP:' in hud[1],
                'not a native tty HUD\n' + self.text())
        require(NAME in hud[0] and 'Lawful' in hud[0], 'wrong player/alignment')
        stats = {}
        for stat in ('St', 'Dx', 'Co', 'In', 'Wi', 'Ch'):
            match = re.search(r'\b' + stat + r':\s*(\S+)', hud[0])
            require(match is not None, 'missing HUD stat ' + stat)
            stats[stat] = match.group(1)
        match = re.search(r'\bT:\s*(\d+)', hud[1])
        require(match is not None, 'time option not visible in native HUD')
        hp = re.search(r'\bHP:\s*(\d+)\((\d+)\)', hud[1])
        require(hp is not None and int(hp.group(1)) > 0, 'player is not alive')
        require(re.search(r'\bDlvl:\s*1\b', hud[1]) is not None,
                'expected first dungeon level')
        # Native tty map is COLNO=80, ROWNO=21, offy=1. Preserve spaces,
        # walls, monsters, objects and player; do not mask dynamic cells.
        dungeon = [line[:80] for line in lines[1:22]]
        x, y = self.screen.cursor.x, self.screen.cursor.y - 1
        require(0 <= x < 80 and 0 <= y < 21 and dungeon[y][x] == '@',
                'native tty cursor does not identify the displayed player')
        require(any(c in ''.join(dungeon) for c in '.-|'), 'empty dungeon map')
        stem = self.snapshot(label)
        state = {'hud': hud, 'stats': stats, 'turn': int(match.group(1)),
                 'hp': [int(hp.group(1)), int(hp.group(2))],
                 'map': dungeon, 'player': [x, y],
                 'coordinate_kind': 'zero-based native 80x21 map viewport'}
        write_json(self.output / (stem + '.json'), state)
        return state

    def inventory(self, before, label):
        self.send('i')
        self.wait(lambda: re.search(r'\(end\)|\(\d+ of \d+\)', self.text()),
                  'complete inventory menu', more=False)
        items, seen_pages = [], set()
        for page in range(20):
            text = self.text()
            marker = re.search(r'\(end\)|\((\d+) of (\d+)\)', text)
            require(marker is not None, 'inventory page marker missing')
            page_key = marker.group(0)
            require(page_key not in seen_pages, 'inventory pagination stalled')
            seen_pages.add(page_key)
            self.snapshot(label + '-page-' + str(page + 1))
            for line in self.screen.display:
                item = re.match(r'^\s*([a-zA-Z$])\s+[-+]\s+(.+?)\s*$', line)
                if item:
                    items.append({'letter': item.group(1), 'description': item.group(2)})
            if marker.group(0) == '(end)' or marker.group(1) == marker.group(2):
                self.send(' ')
                break
            self.send('>')
            expected = int(marker.group(1)) + 1
            self.wait(lambda: '(' + str(expected) + ' of ' in self.text(),
                      'next inventory page', more=False)
        else:
            raise RuntimeError('too many inventory pages')
        self.settle()
        require(items and len({item['letter'] for item in items}) == len(items),
                'inventory must contain distinct exact item rows')
        require(any('spear' in item['description'] for item in items)
                and any('shield' in item['description'] for item in items),
                'native SlashEM Valkyrie inventory lacks spear or shield')
        after = self.live(label + '-closed')
        require(after == before, 'inventory inspection changed HUD, turn or map')
        return items

    def capture(self, label):
        state = self.live(label)
        state['inventory'] = self.inventory(state, label + '-inventory')
        write_json(self.output / (self.label + '-' + label + '-complete.json'), state)
        return state

    def advance(self, before, label):
        # An ordinary game has live hostiles; pets count conservatively too.
        # Choose a displayed empty floor away from visible monster glyphs,
        # rather than spending arbitrary stationary search turns under attack.
        # This is a screen-driven player action, not a seeded or patched world.
        x, y = before['player']
        threats = [(mx, my) for my, row in enumerate(before['map'])
                   for mx, glyph in enumerate(row)
                   if glyph.isascii() and glyph.isalpha()]
        candidates = []
        for dx, dy, key in ((-1, 0, 'h'), (1, 0, 'l'), (0, -1, 'k'), (0, 1, 'j'),
                            (-1, -1, 'y'), (1, -1, 'u'), (-1, 1, 'b'), (1, 1, 'n')):
            nx, ny = x + dx, y + dy
            if not (0 <= nx < 80 and 0 <= ny < 21):
                continue
            if before['map'][ny][nx] != '.':
                continue
            # Native diagonal movement cannot cross doorways or squeeze
            # through two blocked orthogonal neighbours with this inventory.
            if dx and dy and (before['map'][y][x] == '+' or
                              (before['map'][y][nx] in ' |-+' and
                               before['map'][ny][x] in ' |-+')):
                continue
            clearance = min((max(abs(nx - mx), abs(ny - my))
                             for mx, my in threats), default=80)
            candidates.append((clearance, nx, ny, key))
        require(candidates, 'native dungeon has no adjacent visible floor for movement')
        # Stable tie-breaking follows the ordinary vi-key order above. Treat
        # pets conservatively as threats too; no hidden monster state is read.
        clearance, nx, ny, key = max(candidates, key=lambda candidate: candidate[0])
        write_json(self.output / (self.label + '-' + label + '-movement-choice.json'),
                   {'from': [x, y], 'to': [nx, ny], 'key': key,
                    'destination_glyph': '.', 'visible_letter_threats': threats,
                    'clearance': clearance, 'candidates': candidates})
        self.send(key)
        self.wait(lambda: '--More--' not in self.text(), 'native movement')
        moved = self.live(label + '-movement')
        require(moved['turn'] > before['turn'] and moved['player'] == [nx, ny],
                'floor movement did not reach the selected square and advance turn')
        return self.capture(label)

    def save(self):
        self.send('S')
        self.wait(lambda: 'Really save?' in self.text(), 'native save confirmation', more=False)
        self.send('y')
        end = time.monotonic() + 15
        while not self.exited() or not self.eof:
            self.read()
            if '--More--' in self.text() and not self.exited():
                self.send(' ')
            require(time.monotonic() < end, 'native save process did not exit')
        require(self.status == 0, 'native save exited with status ' + str(self.status))
        require(b'Saving' in self.raw, 'native save message absent')
        self.snapshot('saved-exit')

    def close(self):
        if self.transport is not None:
            self.transport.close()
            self.transport = None
        if self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait()
        self.stderr.close()



def fingerprint(path):
    if not path.exists() and not path.is_symlink():
        return None
    if path.is_symlink():
        return {'link': os.readlink(path)}
    if path.is_file():
        return {'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
                'size': path.stat().st_size}
    return {str(child.relative_to(path)): fingerprint(child)
            for child in sorted(path.iterdir())}


def save_file(state, output, label):
    files = [p for p in (state / 'save').rglob('*') if p.is_file()]
    require(len(files) == 1 and files[0].stat().st_size > 0,
            'expected exactly one nonempty native save under private data/slashem/save')
    require(files[0].name == str(os.getuid()) + NAME + '.gz',
            'unexpected native UID/player save name')
    require(files[0].read_bytes().startswith(b'\x1f\x8b'),
            'native gzip compression did not produce a gzip save')
    copy = output / (label + '.native-save')
    shutil.copyfile(files[0], copy)
    return {'path': str(files[0].relative_to(state)),
            'size': copy.stat().st_size,
            'sha256': hashlib.sha256(copy.read_bytes()).hexdigest()}


def isolation_receipt():
    host_net = os.environ['SLASHEM_HOST_NET']
    host_mount = os.environ['SLASHEM_HOST_MOUNT']
    host_pid = os.environ['SLASHEM_HOST_PID']
    network = os.readlink('/proc/self/ns/net')
    mount_namespace = os.readlink('/proc/self/ns/mnt')
    pid_namespace = os.readlink('/proc/self/ns/pid')
    require(network != host_net, 'network namespace unchanged')
    require(mount_namespace != host_mount, 'mount namespace unchanged')
    require(pid_namespace != host_pid, 'PID namespace unchanged')
    interfaces = socket.if_nameindex()
    require(interfaces == [(1, 'lo')],
            'network namespace exposes non-loopback interfaces')
    mount('/gnu/store', '/gnu/store', flags=4096)  # MS_BIND
    mount('/gnu/store', '/gnu/store', flags=4096 | 32 | 1)  # BIND|REMOUNT|RDONLY
    entries = [line for line in Path('/proc/self/mountinfo').read_text().splitlines()
               if line.split()[4] == '/gnu/store']
    require(entries and 'ro' in entries[-1].split()[5].split(','),
            'store bind mount is not read-only')
    return {'host_network_namespace': host_net, 'network_namespace': network,
            'host_mount_namespace': host_mount, 'mount_namespace': mount_namespace,
            'network_interfaces': interfaces, 'store_readonly': True,
            'host_pid_namespace': host_pid, 'pid_namespace': pid_namespace,
            'store_mountinfo': entries[-1]}


def launch_isolated(executable, output):
    unshare = shutil.which('unshare')
    require(unshare is not None, 'realized unshare missing')
    variables = ('PATH', 'HOME', 'TMPDIR', 'GUIX_PYTHONPATH', 'PYTHONPATH',
                 'TERMINFO', 'TERMINFO_DIRS', 'XDG_DATA_HOME', 'XDG_STATE_HOME',
                 'XDG_CONFIG_HOME')
    env = {key: os.environ[key] for key in variables if os.environ.get(key)}
    env.update({'LC_ALL': 'C',
                'SLASHEM_HOST_NET': os.readlink('/proc/self/ns/net'),
                'SLASHEM_HOST_MOUNT': os.readlink('/proc/self/ns/mnt'),
                'SLASHEM_HOST_PID': os.readlink('/proc/self/ns/pid')})
    command = [unshare, '--user', '--map-current-user', '--keep-caps', '--mount', '--propagation',
               'private', '--net', '--pid', '--mount-proc', '--kill-child', '--fork',
               sys.executable, '-B', str(Path(__file__).resolve()), '--inside',
               executable, '--output', str(output)]
    process = subprocess.Popen(command, env=env, start_new_session=True)
    try:
        status = process.wait(timeout=240)
    except BaseException:
        os.killpg(process.pid, signal.SIGKILL)
        process.wait()
        raise
    require(status == 0,
            'isolated proof failed (namespace denial is not a pass): ' + str(status))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('executable', help='installed bin/slashem launcher')
    parser.add_argument('--output', required=True, type=Path, help='new evidence directory')
    parser.add_argument('--inside', action='store_true', help=argparse.SUPPRESS)
    args = parser.parse_args()
    executable = str(Path(args.executable).resolve())
    require(os.access(executable, os.X_OK), "installed SLASH'EM is not executable")
    output = args.output.absolute()
    require(not output.exists(), 'evidence directory already exists; choose a fresh --output')
    if not args.inside:
        launch_isolated(executable, output)
        return
    output.mkdir(parents=True, mode=0o700)
    original_home = Path.home()
    watched = {original_home / '.nethackrc', original_home / '.slashemrc',
               original_home / '.local/share/slashem',
               original_home / '.local/state/slashem', Path.cwd() / 'saves',
               Path.cwd() / 'bones', Path.cwd() / 'level', Path.cwd() / 'dumps',
               Path(executable).parent.parent}
    for variable in ('XDG_DATA_HOME', 'XDG_STATE_HOME', 'XDG_CONFIG_HOME'):
        if os.environ.get(variable):
            watched.add(Path(os.environ[variable]) / 'slashem')
    initial = {str(path): fingerprint(path) for path in watched}
    report = {'success': False, 'executable': executable, 'options': OPTIONS, 'sessions': [], 'continuity': []}
    session = None
    display = None
    try:
        report['isolation'] = isolation_receipt()
        output = private_tmp(output)
        display = Display(output)
        report['isolation']['display'] = display.env['DISPLAY']
        with tempfile.TemporaryDirectory(prefix='slashem-proof-', dir='/tmp') as directory:
            root = Path(directory)
            for name in ('home', 'config', 'data', 'cache', 'state', 'runtime', 'tmp', 'work'):
                (root / name).mkdir(mode=0o700)
            options_path = root / 'config' / 'native-options'
            options_path.write_text('OPTIONS=' + OPTIONS + '\n')
            env = {'HOME': str(root / 'home'), 'TERM': 'xterm-256color',
                   'LC_ALL': 'C', 'PATH': '', 'TMPDIR': str(root / 'tmp'),
                   'MAIL': str(root / 'tmp' / 'no-mailbox'),
                   'NETHACKOPTIONS': '@' + str(options_path)}
            # Guix ncurses may require its explicit read-only terminfo location.
            for variable in ('TERMINFO', 'TERMINFO_DIRS'):
                if os.environ.get(variable):
                    env[variable] = os.environ[variable]
            for variable, subdir in (('XDG_CONFIG_HOME', 'config'), ('XDG_DATA_HOME', 'data'),
                                     ('XDG_CACHE_HOME', 'cache'), ('XDG_STATE_HOME', 'state'),
                                     ('XDG_RUNTIME_DIR', 'runtime')):
                env[variable] = str(root / subdir)
            gui_env = dict(display.env)
            gui_env['TMPDIR'] = str(root / 'tmp')
            state = root / 'data' / 'slashem'
            previous = None
            for number in range(1, 4):
                session = Session(executable, env, root, output, number, gui_env)
                session.wait(lambda: NAME in session.screen.display[22]
                             and 'HP:' in session.screen.display[23], 'native startup')
                raw = session.raw.decode('latin1')
                if number == 1:
                    require("welcome to SlashEM!" in raw and 'welcome back' not in raw,
                            'first process must start a fresh native game')
                else:
                    require('Restoring save file' in raw and 'welcome back' in raw,
                            'fresh process did not restore native save')
                start = session.capture('first-live' if number == 1 else 'restored')
                if previous is not None:
                    # Includes exact raw HUD rows, every map cell, coordinate,
                    # stats, HP, turn and every inventory letter/description.
                    require(start == previous, 'restored state differs from saved state')
                    require(not any(p.is_file() for p in (state / 'save').rglob('*')),
                            'normal native restore did not consume its save')
                    report['continuity'].append({'from': number - 1, 'to': number,
                                                 'exact_fields_map_inventory': True,
                                                 'native_save_consumed': True})
                initial_image = session.image('first-live' if number == 1 else 'restored')
                if number == 3:
                    report['restored_screenshot'] = session.image('restored', filename='restored.png')
                advanced = session.advance(start, 'advanced')
                advanced_image = session.image('advanced')
                session.save()
                saved = save_file(state, output, 'session-' + str(number))
                report['sessions'].append({'argv': session.argv, 'initial': start,
                                           'advanced': advanced, 'native_save': saved,
                                           'exit_status': session.status,
                                           'screenshots': [initial_image, advanced_image]})
                previous = advanced
                session.close()
                session = None
            require(not list((root / 'work').iterdir()), 'state escaped into caller working directory')
            for subdir in ('home', 'cache', 'state', 'runtime'):
                require(not list((root / subdir).iterdir()), 'unexpected state outside XDG data: ' + subdir)
            require(set((root / 'config').iterdir()) == {options_path, root / 'config' / 'slashem'}, 'unexpected config write')
            require(list((root / 'data').iterdir()) == [state],
                    "game state escaped its private SLASH'EM directory")
            for path in root.rglob('*'):
                require(not path.is_symlink(), 'runtime state symlink could escape private root')
            report['private_footprint'] = {str(p.relative_to(root)): p.stat().st_size
                                           for p in root.rglob('*') if p.is_file()}
            require(all(fingerprint(Path(path)) == value for path, value in initial.items()),
                    "SLASH'EM state/config escaped into original home or caller directory")
            report['isolation'].update({'private_environment': env,
                                        'working_directory_empty': True,
                                        'host_game_state_unchanged': True,
                                        'runtime_symlinks_absent': True})
            report['success'] = True
        write_json(output / 'continuity.json', report)
        print('SLASHEM_NATIVE_OK')
    except BaseException as error:
        report['error'] = str(error)
        if session is not None:
            session.snapshot('failure')
            session.close()
        write_json(output / 'continuity.json', report)
        raise
    finally:
        if display is not None:
            display.close()


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == '--relay':
        sys.exit(relay(sys.argv[2:]))
    main()
