;;; GNU Guix package for the official FFglitch source release.

(define-module (tay packages ffglitch)
  #:use-module (guix build-system gnu)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages assembly)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages sdl)
  #:use-module (gnu packages texinfo)
  #:use-module (gnu packages xorg))

(define-public ffglitch
  (package
    (name "ffglitch")
    (version "0.10.2")
    ;; Official release corresponding to ffglitch-core commit
    ;; 225c210d02a30949e7d0443109c4cd2a8bea94d0.
    (source
     (origin
       (method url-fetch)
       (uri (string-append "https://ffglitch.org/pub/src/ffglitch-"
                           version ".tar.xz"))
       (sha256
        (base32 "0vm4bd1al5ixsc8577970mjn25mb9j5vwf1hwi32h10vrvabpv3s"))))
    (build-system gnu-build-system)
    (arguments
     (list
      #:test-target "fate"
      #:configure-flags
      #~(list "--enable-gpl"
              "--enable-static"
              "--disable-shared"
              "--disable-stripping"
              "--enable-runtime-cpudetect"
              "--enable-ffedit"
              "--enable-ffmpeg"
              "--enable-ffplay"
              "--enable-ffprobe"
              "--enable-libzmq"
              "--enable-rtmidi"
              "--enable-sdl2"
              "--enable-alsa"
              "--enable-libxcb"
              "--enable-libxcb-shm"
              "--enable-libxcb-shape"
              "--enable-libxcb-xfixes"
              "--enable-xlib"
              ;; Upstream has no ffedit.texi, only dummy man-page targets.
              ;; Retain generated man pages and the shipped QuickJS HTML docs.
              "--disable-htmlpages"
              "--disable-podpages")
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'unpack 'bind-python-and-fix-helper
            (lambda* (#:key inputs #:allow-other-keys)
              ;; Python scripting is already compiled into libavutil.  Its
              ;; dlopen search must not rely on a mutable host library path.
              ;; Retain upstream's explicit FFGLITCH_LIBPYTHON_PATH override.
              (substitute* "libavutil/script_python.c"
                (("\"libpython3.13.so.1\"")
                 (string-append "\""
                                (search-input-file
                                 inputs
                                 #$(string-append
                                    "lib/libpython"
                                    (version-major+minor
                                     (package-version python))
                                    ".so.1.0"))
                                "\"")))
              (substitute* "libavutil/quickjs/tests/test_std.js"
                (("/bin/sh") (which "sh")))
              (substitute* "ffglitch/ffglitch.py"
                (("ffedit_path = \\[os.path.join\\(dir_path, \"ffedit\"\\)\\]")
                 (string-append "ffedit_path = [\"" #$output "/bin/ffedit\"]"))
                ;; This older helper still used the pre-0.10 positional CLI.
                (("run_ffedit\\(\\[args.input,")
                 "run_ffedit([\"-i\", args.input,")
                (("json_out, args.output\\]")
                 "json_out, \"-o\", args.output]")
                (("#!/usr/bin/env python")
                 (string-append "#!" (search-input-file inputs "bin/python3"))))))
          (add-after 'unpack 'classify-external-fate-samples
            (lambda _
              ;; These three upstream tests use vsynth_lena.yuv, generated
              ;; from external SAMPLES/lena.pnm, but were registered as
              ;; sample-free.  Put them in the normal external-sample group;
              ;; retain every generated-media test and the real references.
              (substitute* "tests/fate/ffmpeg.mak"
                (((string-append "FATE_FFMPEG-(.* \\+= fate-ffmpeg-"
                                 "(filter-in-eof|streamcopy-t|loopback-decoding))")
                  _ registration)
                 (string-append "FATE_SAMPLES_FFMPEG-" registration)))))
          (replace 'configure
            ;; Reuse Guix FFmpeg's custom configure convention, not GNU flags.
            (lambda* (#:key configure-flags #:allow-other-keys)
              (setenv "SHELL" (which "bash"))
              (setenv "CONFIG_SHELL" (which "bash"))
              ;; Also patch the shell script generated by configure's TMPDIR
              ;; sanity probe; source shebang patching cannot see that file.
              (substitute* "configure"
                (("#! */bin/sh") (string-append "#!" (which "sh"))))
              (apply invoke "./configure"
                     (string-append "--prefix=" #$output)
                     (string-append "--datadir=" #$output "/share/ffglitch")
                     (string-append "--docdir=" #$output "/share/doc/ffglitch")
                     configure-flags)))
          (add-after 'build 'build-standalone-quickjs
            (lambda* (#:key make-flags #:allow-other-keys)
              ;; The top-level default target does not include this upstream
              ;; interpreter, which contains FFglitch's MIDI/ZeroMQ modules.
              (apply invoke "make" "qjs" make-flags)))
          (add-before 'check 'set-embedded-python-path
            (lambda _
              (setenv "PYTHONHOME" #$python)
              (setenv "GUIX_PYTHONPATH"
                      #$(file-append
                         python-numpy
                         (string-append "/lib/python"
                                        (version-major+minor
                                         (package-version python))
                                        "/site-packages")))))
          (add-after 'check 'check-bundled-quickjs-and-editing
            (lambda* (#:key tests? make-flags #:allow-other-keys)
              (use-modules (ice-9 rdelim) (srfi srfi-1))
              (define (reference-text file)
                (call-with-input-file file
                  (lambda (port)
                    (let loop ((lines '()))
                      (let ((line (read-line port)))
                        (if (eof-object? line)
                            (reverse lines)
                            (loop (if (string-contains line "\"filename\"")
                                      lines (cons line lines)))))))))
              (when tests?
                ;; Run upstream offline QuickJS tests without rebuilding a
                ;; second, differently configured copy of the interpreter.
                (let ((qjs (string-append (getcwd) "/qjs")))
                  (with-directory-excursion "libavutil/quickjs"
                    (for-each
                     (lambda (test) (invoke qjs test))
                     '("tests/test_closure.js" "tests/test_language.js"
                       "tests/test_builtin.js" "tests/test_loop.js"
                       "tests/test_std.js" "tests/test_worker.js"))))
                ;; All fixtures used by ffedit-tests ship in the release.
                ;; This old harness overwrites its expected files: preserve
                ;; and compare them, ignoring only the build-root filename.
                (let* ((files (append (find-files "tests/ffedit/ref" "\\.ref$")
                                      (find-files "tests/ffedit/json" "\\.json$")))
                       (references (map (lambda (file)
                                          (cons file (reference-text file)))
                                        files)))
                  ;; The upstream scripts assume out-of-tree ./src access.
                  (symlink "." "src")
                  (apply invoke "make" "ffedit-tests" make-flags)
                  (for-each
                   (lambda (reference)
                     (unless (equal? (cdr reference)
                                     (reference-text (car reference)))
                       (error "ffedit regression mismatch" (car reference))))
                   references)
                  (delete-file "src")))))
          (replace 'install
            (lambda _
              ;; Install the fork's applications, not stock FFmpeg names or
              ;; ABI-incompatible libav* headers/libraries/pkg-config files.
              ;; Upstream install-progs omits its ffgac and fflive copies.
              (let ((bin (string-append #$output "/bin"))
                    (data (string-append #$output "/share/ffglitch"))
                    (doc (string-append #$output "/share/doc/ffglitch"))
                    (private (string-append #$output "/libexec/ffglitch")))
                (for-each (lambda (tool) (install-file tool bin))
                          '("ffedit" "ffgac" "fflive"))
                (mkdir-p bin)
                (copy-file "ffprobe" (string-append bin "/ffglitch-ffprobe"))
                (install-file "qjs" private)
                (for-each (lambda (file) (install-file file data))
                          '("ffglitch/ffglitch.js" "ffglitch/ffglitch.py"))
                (for-each (lambda (file) (install-file file doc))
                          '("README.md" "INSTALL.md" "RELEASE_NOTES"
                            "Changelog" "CREDITS" "LICENSE.md"
                            "COPYING.GPLv2" "COPYING.GPLv3"
                            "COPYING.LGPLv2.1" "COPYING.LGPLv3"))
                ;; Keep FFmpeg's generic manuals private to avoid profile
                ;; collisions; public names retain their upstream CLIs.
                (for-each
                 (lambda (file)
                   (unless (zero? (stat:size (stat file)))
                     (install-file file (string-append doc "/man"))))
                 (find-files "doc" "\\.[13]$"))
                (copy-recursively "libavutil/quickjs/doc"
                                  (string-append doc "/quickjs"))
                (for-each
                 (lambda (component)
                   (install-file
                    (string-append (car component) "/LICENSE")
                    (string-append doc "/licenses/" (cdr component))))
                 '(("libavutil/quickjs" . "quickjs")
                   ("libavutil/zeromq" . "zeromq")
                   ("libavutil/rtmidi" . "rtmidi")
                   ("libavcodec/xvidcore" . "xvidcore")))
                ;; These files carry required copyright/disclaimer notices
                ;; not reproduced by the components' license texts alone.
                (for-each
                 (lambda (file)
                   (install-file file (string-append doc "/licenses/source-notices")))
                 '("libavutil/zeromq/external/sha1/sha1.c"
                   "libavutil/quickjs/quickjs-zmq.c"
                   "libavutil/quickjs/quickjs-rtmidi.cpp"
                   "libavcodec/jfdctfst.c" "libavcodec/jfdctint_template.c"
                   "libavcodec/jrevdct.c"))
                (call-with-output-file (string-append doc "/NOTICES")
                  (lambda (port)
                    (display
                     (string-append
                      "FFglitch 0.10.2 is built with GPL components, "
                      "including bundled Xvid.\n"
                      "FFmpeg/FFglitch code is LGPL-2.1-or-later, "
                      "with GPL-2.0-or-later components.\n"
                      "Bundled QuickJS and RtMidi use the Expat license; "
                      "ZeroMQ uses MPL-2.0.\n"
                      "ZeroMQ's bundled SHA-1 implementation uses the "
                      "three-clause BSD license.\n"
                      "This software is based in part on the work of the "
                      "Independent JPEG Group.\n"
                      "The Guix package makes no changes to the three "
                      "IJG-derived source files.\n"
                      "Component licenses and source copyright notices "
                      "are in licenses/.\n\n"
                      "Tools: bin/ffedit, bin/ffgac, bin/fflive, "
                      "bin/ffglitch-ffprobe.\n"
                      "FFglitch's standalone QuickJS: libexec/ffglitch/qjs.\n"
                      "JSON JavaScript helper and media Python helper: "
                      "share/ffglitch/.\n"
                      "Native .py scripting loads the package's Python "
                      "library by default;\n"
                      "FFGLITCH_LIBPYTHON_PATH remains an explicit "
                      "upstream override.\n"
                      "Generic FFmpeg man pages are retained privately "
                      "in this directory's man/.\n")
                     port))))))
          (add-after 'install 'wrap-embedded-python
            (lambda _
              ;; Native Python scripting unconditionally imports NumPy.
              ;; Neither embedded imports nor the stdlib may depend on the
              ;; invoking workstation's profile or Python installation.
              (for-each
               (lambda (tool)
                 (wrap-program (string-append #$output "/bin/" tool)
                   `("PYTHONHOME" = (,#$python))
                   `("GUIX_PYTHONPATH" ":" prefix
                     (,#$(file-append
                          python-numpy
                          (string-append "/lib/python"
                                         (version-major+minor
                                          (package-version python))
                                         "/site-packages"))))))
               '("ffedit" "fflive")))))))
    (native-inputs (list nasm perl pkg-config python-wrapper texinfo))
    ;; QuickJS, RtMidi, ZeroMQ and the x86 Xvid implementation are modified
    ;; in-tree components of this fork, not interchangeable system libraries.
    (inputs (list alsa-lib bash-minimal bzip2 libx11 libxcb libxext libxv
                  python python-numpy sdl2 xz zlib))
    (home-page "https://ffglitch.org/")
    (synopsis "Multimedia bitstream editing and live glitch scripting")
    (description
     "FFglitch is an FFmpeg fork for editing encoded multimedia bitstreams.
It includes ffedit for JSON export, import and native JavaScript or Python
scripting; ffgac for glitch-oriented encoding; and fflive for live scripted
playback.  Its bundled QuickJS interpreter supports ZeroMQ messaging and MIDI.
The applications coexist with stock FFmpeg without replacing its commands or
libraries.")
    (license (list license:gpl2+ license:lgpl2.1+ license:expat
                   license:mpl2.0 license:bsd-3 license:ijg))))
