;;; User-supplied wake assets for the pinned Hermes Agent source.
;;; SPDX-License-Identifier: GPL-3.0-or-later

(define-module (tay packages hermes-python-wake)
  #:use-module (guix gexp)
  #:export (hermes-guix-wake-phase))

;; Add after unpack and before installing the source.  Python wrappers remain
;; packaged; licensed engine binaries and model files belong to the user.
(define hermes-guix-wake-phase
  #~(lambda _
      (use-modules (ice-9 textual-ports) (srfi srfi-1) (srfi srfi-13))
      ;; Fail on upstream drift instead of retaining an automatic downloader.
      (define (patch file replacements)
        (let* ((source (call-with-input-file file get-string-all))
               (patched
                (fold
                 (lambda (replacement text)
                   (let* ((old (car replacement))
                          (new (cdr replacement))
                          (start (string-contains text old)))
                     (unless (and start
                                  (not (string-contains text old
                                                        (+ start (string-length old)))))
                       (error "Hermes wake patch no longer matches" file old))
                     (string-append
                      (substring text 0 start) new
                      (substring text (+ start (string-length old))))))
                 source replacements)))
          (call-with-output-file file
            (lambda (port) (display patched port)))))
      (patch
       "tools/wake_word.py"
       '(
         ("# Bundled \"hey hermes\" model (tools/wakewords/) — the default; alias names resolve\n# to it, not to an openWakeWord built-in.\n_BUNDLED_MODEL_NAME = \"hey_hermes\"\n_BUNDLED_MODEL_ALIASES = frozenset({\"\", \"hey_hermes\", \"hey hermes\", \"hermes\"})\n\n\ndef _bundled_wakeword_path(framework: str = \"onnx\") -> str:\n    \"\"\"Path to the shipped hey_hermes model (.onnx/.tflite) for ``framework``.\"\"\"\n    ext = \"tflite\" if str(framework).strip().lower() == \"tflite\" else \"onnx\"\n    return os.path.join(os.path.dirname(__file__), \"wakewords\", f\"{_BUNDLED_MODEL_NAME}.{ext}\")\n"
          . "# Default \"hey hermes\" name resolves only in the user's model directory.\n_DEFAULT_MODEL_NAME = \"hey_hermes\"\n_DEFAULT_MODEL_ALIASES = frozenset({\"\", \"hey_hermes\", \"hey hermes\", \"hermes\"})\n\n\ndef _wake_model_dir() -> Path:\n    \"\"\"User-supplied models; never create directories or download assets.\"\"\"\n    from hermes_constants import get_hermes_home\n    configured = (os.getenv(\"HERMES_WAKE_MODEL_DIR\") or \"\").strip()\n    return (Path(os.path.expandvars(configured)).expanduser() if configured\n            else get_hermes_home() / \"wakewords\")\n\n\ndef _default_wakeword_path(framework: str = \"onnx\") -> str:\n    \"\"\"Path to the user-supplied hey_hermes model for the selected framework.\"\"\"\n    ext = \"tflite\" if str(framework).strip().lower() == \"tflite\" else \"onnx\"\n    return str(_wake_model_dir() / f\"{_DEFAULT_MODEL_NAME}.{ext}\")\n")))
      (patch
       "tools/wake_word_engines.py"
       '(
         ("def _looks_like_path(value: str) -> bool:\n    return os.sep in value or value.endswith((\".onnx\", \".tflite\", \".ppn\")) or os.path.exists(value)\n"
          . "def _required_file(value: str, setting: str) -> str:\n    \"\"\"Resolve a user-supplied asset without vendor defaults or downloads.\"\"\"\n    value = str(value or \"\").strip()\n    if not value:\n        raise RuntimeError(f\"Set {setting} to a licensed local file; Guix does not \"\n                           \"bundle or download wake-word assets.\")\n    path = Path(os.path.expandvars(value)).expanduser().resolve()\n    if not path.is_file():\n        raise RuntimeError(f\"Wake-word asset not found: {path}. Set {setting} to \"\n                           \"an existing licensed file; no automatic download is performed.\")\n    return str(path)\n")
         ("        import openwakeword\n        from openwakeword.model import Model\n        model_ref = str(sub.get(\"model\") or ww._BUNDLED_MODEL_NAME).strip()\n        framework = self._usable_framework(ww.resolve_inference_framework(cfg))\n        self._threshold = ww._sensitivity(cfg)\n        self._confirm_needed = ww._confirmation_frames(cfg)\n        self._confirm_streak = 0\n        # Default (or explicit \"hey_hermes\") → the bundled model; built-in names / paths as-is.\n        if model_ref.lower() in ww._BUNDLED_MODEL_ALIASES:\n            model_ref = ww._bundled_wakeword_path(framework)\n        # download_models() also fetches the shared feature models (melspectrogram +\n        # embedding) needed for ANY model, so a custom path must call it too.\n        try:\n            openwakeword.utils.download_models([model_ref])\n        except Exception as e:  # pragma: no cover - network/path dependent\n            logger.debug(\"openwakeword model download skipped: %s\", e)\n        self._model = Model(wakeword_models=[model_ref], inference_framework=framework)\n        self._labels = list(self._model.models.keys())\n"
          . "        from openwakeword.model import Model\n        model_ref = str(sub.get(\"model\") or ww._DEFAULT_MODEL_NAME).strip()\n        framework = self._usable_framework(ww.resolve_inference_framework(cfg))\n        if framework not in (\"onnx\", \"tflite\"):\n            raise RuntimeError(\"Set wake_word.openwakeword.inference_framework to onnx or tflite.\")\n        self._threshold = ww._sensitivity(cfg)\n        self._confirm_needed = ww._confirmation_frames(cfg)\n        self._confirm_streak = 0\n        if model_ref.lower() in ww._DEFAULT_MODEL_ALIASES:\n            model_ref = ww._default_wakeword_path(framework)\n        model_ref = _required_file(model_ref, \"wake_word.openwakeword.model\")\n        model_dir = ww._wake_model_dir()\n        melspec = _required_file(\n            sub.get(\"melspectrogram_model_path\") or str(model_dir / f\"melspectrogram.{framework}\"),\n            \"wake_word.openwakeword.melspectrogram_model_path or HERMES_WAKE_MODEL_DIR\")\n        embedding = _required_file(\n            sub.get(\"embedding_model_path\") or str(model_dir / f\"embedding_model.{framework}\"),\n            \"wake_word.openwakeword.embedding_model_path or HERMES_WAKE_MODEL_DIR\")\n        # openWakeWord 0.6 forwards these kwargs to AudioFeatures. VAD remains\n        # disabled (the upstream default), so no fourth model is required.\n        self._model = Model(wakeword_models=[model_ref], inference_framework=framework,\n                            melspec_model_path=melspec, embedding_model_path=embedding)\n        self._labels = list(self._model.models.keys())\n")
         ("# sherpa-onnx open-vocabulary KWS model: small streaming zipformer transducer (English,\n# GigaSpeech), downloaded once under HERMES_HOME. Keywords are tokenized at RUNTIME.\n_SHERPA_KWS_MODEL_URL = (\n    \"https://github.com/k2-fsa/sherpa-onnx/releases/download/kws-models/\"\n    \"sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01.tar.bz2\"\n)\n_SHERPA_KWS_MODEL_DIR = \"sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01\"\n\n\ndef _sherpa_model_root() -> Path:\n    from hermes_constants import get_hermes_home\n    return get_hermes_home() / \"cache\" / \"wakewords\"\n\n\ndef _ensure_sherpa_model(root: Optional[Path] = None) -> Path:\n    \"\"\"Download + unpack the sherpa KWS model once; return its directory.\"\"\"\n    root = root or _sherpa_model_root()\n    target = root / _SHERPA_KWS_MODEL_DIR\n    if (target / \"tokens.txt\").exists():\n        return target\n    import tarfile\n    import urllib.request\n    root.mkdir(parents=True, exist_ok=True)\n    archive = root / f\"{_SHERPA_KWS_MODEL_DIR}.tar.bz2\"\n    logger.info(\"wake word: downloading sherpa KWS model (one-time, ~13 MB)\")\n    urllib.request.urlretrieve(_SHERPA_KWS_MODEL_URL, archive)  # noqa: S310\n    with tarfile.open(archive, \"r:bz2\") as tf:\n        tf.extractall(root, filter=\"data\")\n    archive.unlink(missing_ok=True)\n    if not (target / \"tokens.txt\").exists():\n        raise RuntimeError(f\"sherpa KWS model unpack failed: {target}\")\n    return target\n\n\n"
          . "")
         ("        model_dir = str(sub.get(\"model_dir\") or \"\").strip()\n        d = Path(model_dir) if model_dir else _ensure_sherpa_model()\n        if not (d / \"tokens.txt\").exists():\n            raise RuntimeError(f\"sherpa KWS model not found at {d}\")\n\n"
          . "        model_dir = str(sub.get(\"model_dir\") or \"\").strip()\n        if not model_dir:\n            raise RuntimeError(\"Set wake_word.sherpa.model_dir to a licensed local KWS \"\n                               \"model directory containing tokens.txt, bpe.model, and \"\n                               \"encoder/decoder/joiner ONNX files; Guix does not download models.\")\n        d = Path(os.path.expandvars(model_dir)).expanduser().resolve()\n        if not d.is_dir():\n            raise RuntimeError(f\"sherpa KWS model directory not found: {d}. \"\n                               \"Set wake_word.sherpa.model_dir to an existing local directory.\")\n        _required_file(str(d / \"tokens.txt\"), \"wake_word.sherpa.model_dir (tokens.txt)\")\n        _required_file(str(d / \"bpe.model\"), \"wake_word.sherpa.model_dir (bpe.model)\")\n\n        def _model_file(part: str) -> str:\n            hits = sorted(p for p in d.glob(f\"{part}-*[!8].onnx\") if p.is_file())\n            if not hits:\n                raise RuntimeError(f\"sherpa KWS model file missing: {d}/{part}-*[!8].onnx. \"\n                                   \"Supply a compatible KWS model in wake_word.sherpa.model_dir.\")\n            return str(hits[0])\n\n        # Check all supplied model files before creating the runtime keyword file.\n        encoder, decoder, joiner = (_model_file(part) for part in (\"encoder\", \"decoder\", \"joiner\"))\n\n")
         ("        def _model_file(part: str) -> str:\n            hits = sorted(d.glob(f\"{part}-*[!8].onnx\"))\n            if not hits:\n                raise RuntimeError(f\"sherpa KWS model file missing: {d}/{part}-*[!8].onnx\")\n            return str(hits[0])\n\n"
          . "")
         ("            tokens=str(d / \"tokens.txt\"), encoder=_model_file(\"encoder\"), decoder=_model_file(\"decoder\"),\n            joiner=_model_file(\"joiner\"), keywords_file=self._keywords_file, keywords_threshold=threshold,"
          . "            tokens=str(d / \"tokens.txt\"), encoder=encoder, decoder=decoder,\n            joiner=joiner, keywords_file=self._keywords_file, keywords_threshold=threshold,")
         ("        keyword = str(sub.get(\"keyword\") or \"jarvis\").strip()\n        # Porcupine's `sensitivities` runs the OPPOSITE way to our shared knob (higher =\n        # looser); invert so \"higher = stricter\" holds for every engine.\n        kwargs: Dict[str, Any] = {\"access_key\": access_key, \"sensitivities\": [1.0 - ww._sensitivity(cfg)]}\n        kwargs[\"keyword_paths\" if _looks_like_path(keyword) else \"keywords\"] = [keyword]\n        self._porcupine = pvporcupine.create(**kwargs)\n"
          . "        keyword = str(sub.get(\"keyword\") or \"\").strip()\n        if not keyword.lower().endswith(\".ppn\"):\n            raise RuntimeError(\"Set wake_word.porcupine.keyword to a licensed local .ppn \"\n                               \"keyword file for this platform; bundled keyword names \"\n                               \"are not available in the Guix package.\")\n        keyword_path = _required_file(keyword, \"wake_word.porcupine.keyword\")\n        library_path = _required_file(\n            sub.get(\"library_path\") or os.getenv(\"HERMES_PORCUPINE_LIBRARY\"),\n            \"wake_word.porcupine.library_path or HERMES_PORCUPINE_LIBRARY\")\n        model_path = _required_file(\n            sub.get(\"model_path\") or os.getenv(\"HERMES_PORCUPINE_MODEL\"),\n            \"wake_word.porcupine.model_path or HERMES_PORCUPINE_MODEL\")\n        # Preserve Hermes' shared sensitivity convention (higher = stricter).\n        self._porcupine = pvporcupine.create(\n            access_key=access_key, library_path=library_path, model_path=model_path,\n            keyword_paths=[keyword_path], sensitivities=[1.0 - ww._sensitivity(cfg)])\n")))
      #t))
