;;; Tetraworld and its pinned arsd source closure.
(define-module (tay packages tetraworld)
  #:use-module (gnu packages build-tools)
  #:use-module (gnu packages dlang)
  #:use-module (gnu packages xorg)
  #:use-module (guix build-system gnu)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages))

(define tetraworld-arsd
  (origin
    (method url-fetch)
    (uri "https://codeload.github.com/adamdruppe/arsd/tar.gz/d5c35392931925ca75fe3a399de6c254b57673b0")
    (file-name "tetraworld-arsd-d5c3539.tar.gz")
    (sha256
     (base32 "0kkmkdlgdxmx0qad6s1az3mwllpalm836973xraqq3i1h2xp1p8c"))))

(define arsd-boost-license
  (plain-file
   "BOOST-LICENSE.txt"
   "Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the \"Software\") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"))

(define-public tetraworld
  (package
    (name "tetraworld")
    (version "0-unstable-20210406")
    (source
     (origin
       (method url-fetch)
       (uri (string-append
             "https://codeload.github.com/blargdag/tetraworld/tar.gz/"
             "14f5ca8265db8be91266922ea1718579d1481d68"))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "0i623dkd8qp535vilizdmaz5w4c4h5n38j18j6nbvpj97gma0kbd"))
       (modules '((guix build utils)))
       (snippet
        #~(begin
            ;; Never carry upstream release binaries or its SCP utility into
            ;; the build.  Prefabs are compiled into the executable by import.
            (delete-file-recursively "releases")
            (delete-file "upload.d")
            (delete-file "upload.files")))))
    (build-system gnu-build-system)
    (native-inputs (list ldc scons))
    (inputs (list libx11 libxext libxrender libxft libxtst))
    (arguments
     (list
      #:phases
      #~(modify-phases %standard-phases
          (delete 'configure)
          (add-after 'unpack 'prepare-offline-source
            (lambda _
              (invoke "tar" "-xzf" #$tetraworld-arsd
                      "--strip-components=1" "-C" "arsd")
              ;; Modern D requires const hashing for custom-equality AA keys.
              ;; Pos forwards vector equality via alias-this; hash the same
              ;; coordinate values, never padding or object identity.
              (substitute* "vector.d"
                (("    bool opEquals")
                 (string-append
                  "    size_t toHash() const nothrow @safe {"
                  " return hashOf(impl); }\n\n    bool opEquals")))
              (substitute* "components.d"
                (("    this\\(int\\[4\\] _coors")
                 (string-append
                  "    size_t toHash() const nothrow @safe {"
                  " return coors.toHash(); }\n\n    this(int[4] _coors")))
              ;; Restored special agents already have queued turns. Skip only
              ;; that registration, then process/clear all pending agents.
              (substitute* "agent.d"
                (("                return;")
                 "                continue;"))
              (substitute* "SConstruct"
                (("/usr/src/d/ldc/latest/bin/ldc2")
                 (string-append #$ldc "/bin/ldc2"))
                ;; SCons' default ENV replaces Guix's PATH and cannot find sh.
                (("env = Environment\\(")
                 "env = Environment(ENV=dict(os.environ),")
                ;; The GUI draws software cells; unrelated OpenGL and desktop
                ;; notification features are not used by either game backend.
                (("ldcflags = \\[ \\]")
                 (string-append
                  "ldcflags = ['-gcc=gcc', '-d-version=without_opengl', "
                  "'-d-version=without_libnotify', '-L-ldl']"))
                ;; Explicitly avoid main even if a target has no unit tests.
                (("\"\\./%s\" % testprog")
                 "\"./%s --DRT-testmode=test-only\" % testprog"))
              ;; arsd opens X libraries dynamically, so ELF runpaths alone do
              ;; not capture their names.  Resolve them without a wrapper or
              ;; dependence on an ambient LD_LIBRARY_PATH.
              (substitute* "arsd/simpledisplay.d"
                (("dlopen\\(\"lib\" ~ library ~ \"\\.so\", RTLD_NOW\\)")
                 (string-append
                  "dlopen((library == \"X11\" ? \"" #$libx11 "/lib/libX11.so\" : "
                  "library == \"Xext\" ? \"" #$libxext "/lib/libXext.so\" : "
                  "library == \"Xrender\" ? \"" #$libxrender "/lib/libXrender.so\" : "
                  "library == \"Xft\" ? \"" #$libxft "/lib/libXft.so\" : "
                  "\"lib\" ~ library ~ \".so\"), RTLD_NOW)"))
                (("\"libXtst\\.so\"")
                 (string-append "\"" #$libxtst "/lib/libXtst.so\"")))))
          (replace 'build
            (lambda _
              ;; This named target runs the upstream unit-test prerequisite,
              ;; but does not build Windows binaries or maintainer utilities.
              (invoke "scons" "tetraworld")))
          (replace 'check
            (lambda* (#:key tests? #:allow-other-keys)
              (when tests?
                (delete-file ".tetraworld-teststamp")
                (invoke "scons" ".tetraworld-teststamp"))))
          (replace 'install
            (lambda _
              (let ((doc (string-append #$output "/share/doc/tetraworld")))
                (install-file "tetraworld" (string-append #$output "/bin"))
                (install-file "LICENSE" doc)
                (install-file "README.md" doc)
                (install-file "arsd/LICENSE" (string-append doc "/arsd"))
                (copy-file #$arsd-boost-license
                           (string-append doc "/arsd/BOOST-LICENSE.txt"))
                (call-with-output-file (string-append doc "/arsd/NOTICE")
                  (lambda (port)
                    (display
                     (string-append
                      "arsd color.d, simpledisplay.d and terminal.d: "
                      "Boost Software License 1.0.\n"
                      "Copyright Adam D. Ruppe, 2011-2021 (simpledisplay.d).\n"
                      "https://www.boost.org/LICENSE_1_0.txt\n")
                     port)))))))))
    (home-page "https://github.com/blargdag/tetraworld")
    (synopsis "Explore a four-dimensional roguelike world")
    (description
     "Tetraworld is a roguelike treasure-hunting game in four-dimensional
space.  It provides console and software-rendered graphical backends, a training
area for four-dimensional movement, and automatic per-user save and restore.
All game data are embedded in the executable; saves and options are written to
@file{~/.tetraworld}.  The package builds the pinned arsd modules from source and
excludes upstream release binaries and upload tools.")
    (license (list license:gpl2+ license:boost1.0))))
