;;; Wenyan compiler and CLI, built from the pinned TypeScript sources.
;;;
;;; SPDX-License-Identifier: AGPL-3.0-or-later

(define-module (tay packages wenyan)
  #:use-module (guix build-system gnu)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages node)
  #:use-module (gnu packages python)
  #:use-module (tay packages auxiliary)
  #:use-module (tay packages starred-s-z)
  #:use-module (tay packages wenyan-npm-sources))

(define %wenyan-npm-helper
  (local-file (search-tay-package-file "files/wenyan-npm.py")))

(define-public wenyan
  (package
    (name "wenyan")
    (version "0.4.0")
    (source (package-source wenyan-lang-wenyan-source))
    (build-system gnu-build-system)
    (arguments
     (list
      #:phases
      #~(modify-phases %standard-phases
          (replace 'configure
            (lambda _
              ;; Preserve upstream's lock-selected placement, including nested
              ;; versions.  No registry resolution or lifecycle scripts run.
              (call-with-output-file ".wenyan-npm-inputs"
                (lambda (port)
                  (for-each
                   (lambda (entry)
                     (format port "~a\t~a\t~a~%"
                             (car entry) (cadr entry) (caddr entry)))
                   (list #$@(map
                             (lambda (path)
                               (let* ((key (assoc-ref %wenyan-npm-path-keys path))
                                      (source (assoc-ref %wenyan-npm-sources key)))
                                 #~(list #$path #$key #$source)))
                             %wenyan-npm-paths)))))
              (call-with-output-file ".wenyan-runtime-paths"
                (lambda (port)
                  (for-each (lambda (path) (format port "~a~%" path))
                            '#$%wenyan-runtime-paths)))
              (invoke "python3" #$%wenyan-npm-helper "prepare"
                      ".wenyan-npm-inputs")
              ;; sync-rpc launches its source worker relative to __dirname.
              ;; Keep the real HTTP-import library external rather than bundle
              ;; it into a path where the worker could not be found.
              (substitute* "webpack.base.config.js"
                (("devtool: 'source-map',")
                 (string-append "devtool: 'source-map',\n"
                                "    externals: { 'sync-request': "
                                "'commonjs sync-request' },")))
              (setenv "PATH" (string-append (getcwd) "/node_modules/.bin:"
                                            (getenv "PATH")))
              (setenv "HOME" (getcwd))
              ;; Webpack 4 uses MD4 for build hashes.  This enables Node's
              ;; compatible crypto provider only while building, not at runtime.
              (setenv "NODE_OPTIONS" "--openssl-legacy-provider")))
          (replace 'build
            (lambda _
              (invoke #$(file-append node-lts "/bin/node")
                      "node_modules/typescript/bin/tsc"
                      "--emitDeclarationOnly" "--declaration"
                      "--declarationDir" "typings")
              ;; All four upstream outputs, including embedded Wenyan standard
              ;; library sources, are generated by its actual webpack rules.
              ;; Unminified output avoids opaque minifier payloads and keeps
              ;; source-level diagnostics useful to consumers.
              (invoke #$(file-append node-lts "/bin/node")
                      "node_modules/webpack-cli/bin/cli.js"
                      "--mode" "development")))
          (replace 'check
            (lambda* (#:key tests? #:allow-other-keys)
              (when tests?
                (invoke #$(file-append node-lts "/bin/node") "-e"
                        (string-append
                         "const fs=require('fs'), assert=require('assert'); "
                         "const wy=require('./dist/core/index.min.js'); "
                         "const code=wy.compile(fs.readFileSync("
                         "'examples/factorial.wy','utf8')); let values=[]; "
                         "wy.evalCompiled(code,{outputHanzi:false,"
                         "output:(...xs)=>values.push(xs)}); "
                         "assert.deepStrictEqual(values,[[120]]); "
                         "console.log('compiled recursive factorial = 120');")))))
          (replace 'install
            (lambda _
              (let ((module (string-append #$output "/lib/node_modules/wenyanlang"))
                    (doc (string-append #$output "/share/doc/wenyan"))
                    (data (string-append #$output "/share/wenyan"))
                    (bin (string-append #$output "/bin")))
                (mkdir-p module)
                (copy-recursively "dist" (string-append module "/dist"))
                (copy-recursively "typings" (string-append module "/typings"))
                (call-with-output-file (string-append module "/package.json")
                  (lambda (port)
                    (display
                     (string-append
                      "{\"name\":\"wenyanlang\",\"version\":\"0.4.0\","
                      "\"license\":\"MIT\",\"main\":\"dist/core/index.min.js\","
                      "\"types\":\"dist/core/index.d.ts\"}\n")
                     port)))
                (invoke "python3" #$%wenyan-npm-helper "install"
                        ".wenyan-npm-inputs" ".wenyan-runtime-paths" #$output)
                (copy-recursively "examples" (string-append data "/examples"))
                (copy-recursively "lib" (string-append data "/lib"))
                (for-each (lambda (file) (install-file file doc))
                          '("LICENSE" "README.md" "README.zh-Hans.md"
                            "README.zh-Hant.md" "CHANGELOG.md"))
                ;; TypeScript's ES5 lowering emits compiler helper code into
                ;; every bundle.  Keep its Apache notice with these outputs.
                (install-file "node_modules/typescript/LICENSE.txt" doc)
                (install-file "node_modules/typescript/CopyrightNotice.txt" doc)
                (mkdir-p bin)
                ;; This is the upstream CLI, with only an immutable interpreter
                ;; shebang.  There is no installed proof mode or fake frontend.
                (substitute* (string-append module "/dist/cli/index.min.js")
                  (("#!/usr/bin/env node")
                   (string-append "#!" #$(file-append node-lts "/bin/node"))))
                ;; Node resolves this symlink to the module, keeping the
                ;; external HTTP import worker beside its runtime closure.
                (chmod (string-append module "/dist/cli/index.min.js") #o755)
                (symlink "../lib/node_modules/wenyanlang/dist/cli/index.min.js"
                         (string-append bin "/wenyan"))))))))
    (inputs (list node-lts))
    (native-inputs (append (list python zstd) (map cdr %wenyan-npm-sources)))
    (home-page "https://github.com/wenyan-lang/wenyan")
    (synopsis "Compiler for the classical Chinese programming language Wenyan")
    (description
     "Wenyan is a programming language whose syntax uses classical Chinese.
This package builds its TypeScript compiler, native command-line interface,
JavaScript runtime and rendering library from source.  It includes the Wenyan
standard library, local examples and generated TypeScript declarations.
Programs can be compiled to JavaScript, Python or Ruby; the command-line tool
also executes JavaScript locally.  The fixed npm build closure is materialized
without registry access or dependency-install scripts, and its redistribution
notices are retained in the installed documentation.")
    (license (list license:expat license:isc license:asl2.0 license:bsd-3))))
