;; Fixed-output agent packages missing from the pinned Guix revision.
;; This file is generated by Goocastle alongside manifest.scm; do not replace it
;; with a host installation or an unpinned npm install.
(use-modules (guix download)
             (guix gexp)
             (guix packages)
             (guix utils)
             (guix build-system copy)
             (gnu packages bash)
             (gnu packages base)
             (gnu packages xorg)
             ((guix licenses) #:prefix license:))

;; Debian's xvfb-run redirects the subject's stderr into stdout.  Runtime
;; evidence validates markers on stdout and retains stderr separately, so keep
;; the packaged lifecycle/display allocator while restoring the invoked
;; command's original streams.
(define-public goocastle-xvfb-run
  (package
    (inherit xvfb-run)
    (name "goocastle-xvfb-run")
    (arguments
     (substitute-keyword-arguments (package-arguments xvfb-run)
       ((#:phases phases)
        #~(modify-phases #$phases
            (add-after 'install 'preserve-command-streams
              (lambda* (#:key outputs #:allow-other-keys)
                (let* ((bin (string-append (assoc-ref outputs "out") "/bin"))
                       (program (string-append bin "/xvfb-run")))
                  (substitute* program
                    ((""[$]@" 2>&1") ""$@""))
                  (rename-file program (string-append bin "/goocastle-xvfb-run")))))))))
    (synopsis "Run X11 commands in Xvfb without merging their output streams")))

(define-public goocastle-gitleaks
  (package
    (name "goocastle-gitleaks")
    (version "8.24.3")
    (source (origin
              (method url-fetch)
              (uri (string-append "https://github.com/gitleaks/gitleaks/releases/download/v" version "/gitleaks_" version "_linux_x64.tar.gz"))
              (sha256 (base32 "17729qzpkhviabj1zvyylifpm4lb8j332p1b2bvci91xj2rf14cr"))))
    (build-system copy-build-system)
    (arguments (list #:install-plan #~'(("gitleaks" "bin/gitleaks"))))
    (supported-systems '("x86_64-linux"))
    (home-page "https://gitleaks.io")
    (synopsis "Secret scanner for Git repositories")
    (description "Pinned Gitleaks release used by Goocastle development and CI checks.")
    (license license:expat)))

(define-public goocastle-codex
  (package
    (name "goocastle-codex")
    (version "0.149.0")
    (source (origin
              (method url-fetch)
              (uri (string-append "https://github.com/openai/codex/releases/download/rust-v" version "/codex-package-x86_64-unknown-linux-musl.tar.gz"))
              (sha256 (base32 "0i1j2bji5vzd6gj30s74bwpbfc5lnqkg74vsx94qvdr050kbl20w"))))
    (build-system copy-build-system)
    (arguments
     (list #:install-plan #~'(("bin/" "bin")
                              ("codex-path/" "codex-path")
                              ("codex-resources/" "codex-resources")
                              ("codex-package.json" "codex-package.json"))
           ;; GNU build-system's unpack phase enters the first top-level
           ;; directory ("bin"), so restore the archive root before copying.
           #:phases #~(modify-phases %standard-phases
                        (add-after 'unpack 'use-package-root
                          (lambda _ (chdir ".."))))))
    (supported-systems '("x86_64-linux"))
    (home-page "https://github.com/openai/codex")
    (synopsis "OpenAI Codex coding agent")
    (description "Pinned upstream Codex package archive for x86_64 Linux. The archive contains the Codex CLI and its required runtime companions without compiling the upstream Rust workspace.")
    (license license:asl2.0)))

(define-public goocastle-opencode
  (package
    (name "goocastle-opencode")
    (version "1.18.19")
    (source (origin
              (method url-fetch)
              (uri (string-append "https://github.com/anomalyco/opencode/releases/download/v" version "/opencode-linux-x64.tar.gz"))
              (sha256 (base32 "1n9bgszzsxgd34bhq8cwc9s8zz29zbk0prhsv7smg6azqn3m9cvv"))))
    (build-system copy-build-system)
    (arguments
     (list #:install-plan #~'(("opencode" "libexec/opencode/"))
           ;; The upstream Bun executable cannot be patched or stripped
           ;; without corrupting its appended payload. Keep it byte-for-byte
           ;; and launch it through the pinned glibc loader instead.
           #:validate-runpath? #f
           #:strip-binaries? #f
           #:phases #~(modify-phases %standard-phases
                        (add-after 'install 'wrap-opencode-runtime
                          (lambda* (#:key inputs outputs #:allow-other-keys)
                            (let* ((out (assoc-ref outputs "out"))
                                   (glibc (assoc-ref inputs "glibc"))
                                   (libdir (string-append glibc "/lib"))
                                   (loader (string-append libdir "/ld-linux-x86-64.so.2"))
                                   (program (string-append out "/libexec/opencode/opencode"))
                                   (bin (string-append out "/bin"))
                                   (wrapper (string-append bin "/opencode"))
                                   (bash (search-input-file inputs "/bin/bash")))
                              (mkdir-p bin)
                              (call-with-output-file wrapper
                                (lambda (port)
                                  (format port "#!~a~%exec ~a --library-path ~a ~a \"$@\"~%"
                                          bash loader libdir program)))
                              (chmod wrapper #o555)))))))
    (inputs (list bash-minimal glibc))
    (supported-systems '("x86_64-linux"))
    (home-page "https://opencode.ai")
    (synopsis "OpenCode coding agent")
    (description "Pinned upstream OpenCode Linux release used by Goocastle Guix manifests.")
    (license license:expat)))

(define-public goocastle-pi
  (package
    (name "goocastle-pi")
    (version "0.73.1")
    (source (origin
              (method url-fetch)
              (uri (string-append "https://github.com/earendil-works/pi/releases/download/v" version "/pi-linux-x64.tar.gz"))
              (sha256 (base32 "0v9ngsrxarzrij85lqwv6yjrzppyxas7akdvn7g37fpnjfgdpw00"))))
    (build-system copy-build-system)
    (arguments
     (list #:install-plan #~'(("pi" "libexec/pi/"))
           ;; The upstream Bun executable contains an appended payload that
           ;; must remain byte-for-byte intact. Keep it unmodified and launch
           ;; it through the pinned Guix glibc loader instead.
           #:validate-runpath? #f
           #:strip-binaries? #f
           #:phases #~(modify-phases %standard-phases
                        (add-after 'install 'wrap-pi-runtime
                          (lambda* (#:key inputs outputs #:allow-other-keys)
                            (let* ((out (assoc-ref outputs "out"))
                                   (glibc (assoc-ref inputs "glibc"))
                                   (libdir (string-append glibc "/lib"))
                                   (loader (string-append libdir "/ld-linux-x86-64.so.2"))
                                   (program (string-append out "/libexec/pi/pi"))
                                   (bin (string-append out "/bin"))
                                   (wrapper (string-append bin "/pi"))
                                   (bash (search-input-file inputs "/bin/bash")))
                              (mkdir-p bin)
                              (call-with-output-file wrapper
                                (lambda (port)
                                  (format port "#!~a~%exec ~a --library-path ~a ~a \"$@\"~%"
                                          bash loader libdir program)))
                              (chmod wrapper #o555)))))))
    (inputs (list bash-minimal glibc))
    (supported-systems '("x86_64-linux"))
    (home-page "https://github.com/earendil-works/pi")
    (synopsis "Pi coding agent")
    (description "Pinned upstream Pi Linux release used by Goocastle Guix manifests.")
    (license license:expat)))
