;;; GNU Guix package for TinyFugue Rebirth.

(define-module (tay packages tinyfugue)
  #:use-module (guix build-system gnu)
  #:use-module (guix git-download)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module ((guix licenses)
                #:prefix license:)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages ncurses)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages pcre)
  #:use-module (gnu packages tls))

(define-public tinyfugue
  (package
    (name "tinyfugue")
    (version "5.2.2")
    (source
     (origin
       ;; Use the immutable release commit rather than a moving branch or
       ;; tag.  git-fetch avoids depending on GitHub's autogenerated tarball
       ;; layout while retaining the complete source tree.
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/ingwarsw/tinyfugue")
             (commit "d9e519a92a76d23e889a0d2717266fdaa3578531")))
       (file-name (git-file-name name version))
       (sha256
        (base32 "0c0cnc9wl2q4lgrd6v9f7va2mn379grs6dxvc84xsdbnfb8jwy4w"))))
    (build-system gnu-build-system)
    (arguments
     (list
      ;; The release has no check target or automated test suite.  Keep the
      ;; build offline and exercise the installed client in tests/tinyfugue-
      ;; smoke.sh instead.
      #:tests? #f
      #:configure-flags
      #~(list
         ;; Use Guix's shared libraries for the required PCRE2, zlib,
         ;; ncurses/termcap, and OpenSSL features.  These are discovered by
         ;; configure through the build environment and pcre2-config.
         "--enable-termcap=ncurses"
         "--enable-ssl"
         ;; Protocol features do not add external dependencies.
         "--enable-atcp"
         "--enable-gmcp"
         "--enable-option102"
         ;; Keep the installed command and its data directory unversioned.
         "--disable-version"
         "--disable-symlink"
         ;; Optional integrations are deliberately not part of this baseline:
         ;; the Python embedding patch targets obsolete Python versions, Lua
         ;; needs a separate ABI/runtime decision, and ICU widechar support
         ;; would add a large optional dependency.  Lua is intentionally left
         ;; unspecified: upstream's configure macro enables it for either
         ;; --enable-lua or --disable-lua, so omitting the option is the only
         ;; way to select its default-disabled branch.  Mail probing can
         ;; otherwise capture a host-specific spool path in the build.
         "--disable-python"
         "--disable-widechar"
         "--disable-mailcheck")
      #:phases
      #~(modify-phases %standard-phases
          (add-before 'configure 'set-release-version
            (lambda _
              (use-modules (guix build utils))
              ;; GitHub's source archive has no .git directory, so the
              ;; generated configure script would otherwise label the binary
              ;; "development" even though this is a release build.
              (substitute* "configure"
                (("TFVER=[^[:cntrl:]]*development[^[:cntrl:]]*")
                 (string-append "TFVER=\""
                                #$version "\"")))))
          (add-before 'configure 'set-pcre2-config
            (lambda _
              ;; pcre2-config is a build helper shipped by pcre2.  Set it
              ;; explicitly to the native instance so cross builds never try
              ;; to execute the target-architecture helper.
              (setenv "PCRE_CONFIG"
                      (string-append #+pcre2 "/bin/pcre2-config"))))
          (add-after 'install 'install-documentation
            (lambda _
              (use-modules (guix build utils))
              (let ((doc (string-append #$output "/share/doc/tinyfugue"))
                    (man (string-append #$output "/share/man/man1")))
                (mkdir-p doc)
                (mkdir-p man)
                ;; Keep the complete GPL-2.0-only notice and the upstream
                ;; copyright/component notices with the installed program.
                (install-file "COPYING" doc)
                (install-file "CREDITS" doc)
                (install-file "README.md" doc)
                (install-file "README.orig" doc)
                (install-file "README.python" doc)
                (install-file "unix/README" doc)
                (copy-file "src/tf.1.nroffman"
                           (string-append man "/tf.1")))))
          (add-after 'install-documentation 'wrap-tls-trust
            (lambda _
              ;; Upstream uses OpenSSL's default trust lookup.  Point it at a
              ;; package-owned CA bundle instead of ambient system paths.
              (wrap-program (string-append #$output "/bin/tf")
                `("SSL_CERT_FILE" =
                  (,(string-append
                     #$nss-certs
                     "/etc/ssl/certs/ca-certificates.crt")))))))))
    ;; Referencing nss-certs in the wrapper gexp records it directly in the
    ;; output closure; it is not also needed as a conventional build input.
    (inputs (list bash-minimal ncurses openssl pcre2 zlib))
    (synopsis "Programmable terminal MUD client")
    (description
     "TinyFugue is a programmable terminal client for MUD servers.  It
supports macros, triggers, scripting hooks, scrollback, MCCP compression,
TLS, IPv6, and protocol extensions including ATCP, GMCP, and option 102.
This package builds the PCRE2, zlib, ncurses, and OpenSSL feature set without
network access; optional Python, Lua, ICU wide-character, and mail-checking
features are disabled pending separate compatibility decisions.  The
upstream GPL-2.0-only notice and project documentation are installed under
@file{share/doc/tinyfugue}.")
    (home-page "https://github.com/ingwarsw/tinyfugue")
    (license license:gpl2)))
